import { useEffect, useState } from 'react';
import { ArrowUpRight, Award, BriefcaseBusiness, Check, ChevronDown, ChevronLeft, ChevronRight, Code2, Download, ExternalLink, GraduationCap, Images, Mail, Menu, MessageCircle, ShieldCheck, Terminal, TestTube2, X } from 'lucide-react';
import { FaInstagram } from 'react-icons/fa';
import { portfolio } from './data/portfolio';

const navItems = [['home', 'Home'], ['about', 'About'], ['experience', 'Experience'], ['skills', 'Skills'], ['projects', 'Projects'], ['certifications', 'Certifications'], ['education', 'Education'], ['gallery', 'Gallery'], ['contact', 'Contact']];

function useTypewriter(words) {
  const [state, setState] = useState({ word: words[0], index: 0, deleting: false });
  useEffect(() => {
    const current = words[state.index];
    const done = !state.deleting && state.word === current;
    const empty = state.deleting && state.word === '';
    const delay = done ? 1800 : empty ? 350 : state.deleting ? 45 : 78;
    const timer = setTimeout(() => {
      if (done) setState({ word: current, index: state.index, deleting: true });
      else if (empty) setState({ word: '', index: (state.index + 1) % words.length, deleting: false });
      else setState({ word: state.deleting ? current.slice(0, state.word.length - 1) : current.slice(0, state.word.length + 1), index: state.index, deleting: state.deleting });
    }, delay);
    return () => clearTimeout(timer);
  }, [state, words]);
  return state.word;
}

function SectionHeading({ eyebrow, title, copy }) {
  return <div className="section-heading"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{copy && <p className="section-copy">{copy}</p>}</div>;
}

function Navbar() {
  const [open, setOpen] = useState(false);
  const [active, setActive] = useState('home');
  useEffect(() => {
    const observer = new IntersectionObserver(entries => entries.forEach(entry => entry.isIntersecting && setActive(entry.target.id)), { rootMargin: '-25% 0px -65% 0px' });
    navItems.forEach(([id]) => document.getElementById(id) && observer.observe(document.getElementById(id)));
    return () => observer.disconnect();
  }, []);
  return <header className="site-header"><a className="brand" href="#home" aria-label="Jayant Bansal home"><span className="brand-mark">JB</span><span>Jayant<span className="brand-dot">.</span></span></a><button className="menu-button" onClick={() => setOpen(!open)} aria-label="Toggle navigation" aria-expanded={open}>{open ? <X size={20} /> : <Menu size={20} />}</button><nav className={open ? 'nav-open' : ''}>{navItems.map(([id, label]) => <a key={id} className={active === id ? 'active' : ''} href={`#${id}`} onClick={() => setOpen(false)}>{label}</a>)}</nav><a className="header-cta" href="#contact">Let's talk <ArrowUpRight size={15} /></a></header>;
}

function Hero() {
  const typed = useTypewriter(portfolio.heroTitles);
  return <section id="home" className="hero section-shell"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> Available for QA opportunities</p><h1>Hi, I'm <span className="gradient-text">Jayant Bansal</span></h1><div className="role-line"><span className="role-label">I am a</span><span className="typed" aria-live="polite"><span className="motion-title">{typed}</span><span className="cursor">|</span><span className="static-title">Automation Test Engineer</span></span></div><p className="hero-description">I build dependable test automation that gives teams confidence in every release, from browser workflows to API contracts and CI pipelines.</p><div className="hero-actions"><a className="button button-primary" href={portfolio.person.resume} download>Download resume <Download size={16} /></a><a className="button button-ghost" href="#projects">View projects <ArrowUpRight size={16} /></a></div><div className="hero-proof"><span><ShieldCheck size={17} /> Evidence-led testing</span><span><Terminal size={17} /> Java · Selenium · Playwright</span></div></div><div className="hero-visual"><div className="visual-orbit orbit-one" /><div className="visual-orbit orbit-two" /><div className="portrait-frame"><img src={portfolio.person.portrait} alt="Portrait of Jayant Bansal" /></div><div className="floating-note note-top"><TestTube2 size={17} /><span>Quality first<br /><b>Every release</b></span></div><div className="floating-note note-bottom"><span className="mini-check"><Check size={13} /></span><span>Automation<br /><b>in progress</b></span></div></div><a className="scroll-cue" href="#about" aria-label="Scroll to about"><span>Scroll to explore</span><ChevronDown size={17} /></a></section>;
}

function About() { return <section id="about" className="section-shell section-block"><SectionHeading eyebrow="01 / About" title="Testing with intention." copy={portfolio.summary} /><div className="about-grid"><div className="about-statement"><span className="quote-mark">“</span><p>I turn requirements into testable behavior, then make that behavior repeatable, visible, and trustworthy.</p><div className="signature-line"><span /> Jayant Bansal</div></div><div className="capability-grid">{[['QA Automation', ShieldCheck], ['UI Testing', Images], ['API Testing', Code2], ['Manual Testing', TestTube2]].map(([label, Icon]) => <div className="capability" key={label}><Icon size={22} /><span>{label}</span></div>)}</div></div></section>; }

function Experience() { return <section id="experience" className="section-shell section-block"><SectionHeading eyebrow="02 / Experience" title="Making quality visible." /><div className="experience-card"><div className="experience-top"><div><span className="date-tag">Sep 2026 - Present</span><h3>Software Quality Assurance Tester</h3><p className="company">SkillNexus <span>· Remote</span></p></div><BriefcaseBusiness className="experience-icon" size={30} /></div><div className="experience-body"><p>Hands-on quality work across test planning, end-to-end execution, defect reporting, and release-ready documentation.</p><div className="experience-points">{portfolio.experience.points.map(point => <div key={point}><Check size={16} />{point}</div>)}</div></div><div className="tag-row"><span>Manual testing</span><span>Functional testing</span><span>Jira</span><span>Defect management</span><span>Test reporting</span></div></div></section>; }

function Metrics() { return <div className="metrics section-shell" aria-label="Testing metrics">{portfolio.metrics.map(([number, label]) => <div className="metric" key={label}><strong>{number}</strong><span>{label}</span></div>)}</div>; }

function Skills() { return <section id="skills" className="section-shell section-block"><SectionHeading eyebrow="03 / Skills" title="A practical toolkit." copy="The tools and methods I use to make software more resilient." /><div className="skills-grid">{Object.entries(portfolio.skills).map(([category, skills]) => <div className="skill-group" key={category}><div className="skill-heading"><span className="skill-number">0{Object.keys(portfolio.skills).indexOf(category) + 1}</span><h3>{category}</h3></div><div className="chip-list">{skills.map(skill => <span key={skill}>{skill}</span>)}</div></div>)}</div></section>; }

function Lightbox({ images, index, onClose, onChange }) { const hasMultiple = images.length > 1; useEffect(() => { const handler = event => { if (event.key === 'Escape') onClose(); if (event.key === 'ArrowLeft') onChange((index - 1 + images.length) % images.length); if (event.key === 'ArrowRight') onChange((index + 1) % images.length); }; document.addEventListener('keydown', handler); document.body.style.overflow = 'hidden'; return () => { document.removeEventListener('keydown', handler); document.body.style.overflow = ''; }; }, [images.length, index, onChange, onClose]); return <div className="lightbox" role="dialog" aria-modal="true" aria-label={`Project screenshot ${index + 1} of ${images.length}`} onMouseDown={event => event.target === event.currentTarget && onClose()}><button className="lightbox-close" onClick={onClose} aria-label="Close screenshots"><X /></button>{hasMultiple && <button className="lightbox-nav lightbox-prev" onClick={() => onChange((index - 1 + images.length) % images.length)} aria-label="Previous screenshot"><ChevronLeft /></button>}<img src={images[index]} alt={`Expanded project screenshot ${index + 1} of ${images.length}`} />{hasMultiple && <button className="lightbox-nav lightbox-next" onClick={() => onChange((index + 1) % images.length)} aria-label="Next screenshot"><ChevronRight /></button>}{hasMultiple && <div className="lightbox-dots" aria-label="Choose project screenshot">{images.map((image, imageIndex) => <button key={image} className={imageIndex === index ? 'active' : ''} onClick={() => onChange(imageIndex)} aria-label={`Show screenshot ${imageIndex + 1}`} aria-current={imageIndex === index ? 'true' : undefined} />)}</div>}</div>; }

function ProjectCard({ project, onImage }) { const [activeImage, setActiveImage] = useState(0); useEffect(() => { if (project.images.length < 2) return undefined; const timer = setInterval(() => setActiveImage(current => (current + 1) % project.images.length), 4800); return () => clearInterval(timer); }, [project.images.length]); return <article className="project-card"><button className="project-image-button" onClick={() => onImage(project.images)} aria-label={`Open ${project.title} screenshots`}><div className="project-carousel" aria-live="polite">{project.images.map((image, imageIndex) => <img key={image} className={imageIndex === activeImage ? 'active' : ''} src={image} alt={`${project.title} interface screenshot ${imageIndex + 1}`} loading={imageIndex === 0 ? 'lazy' : undefined} />)}</div><span className="image-overlay" title={`View ${project.images.length} screenshots`}><Images size={16} aria-hidden="true" /></span></button><div className="project-content"><div className="project-kicker"><span>Case study 0{project.title.startsWith('Government') ? '1' : '2'}</span><a href={project.github} target="_blank" rel="noreferrer" aria-label={`Open ${project.title} on GitHub`}><Code2 size={18} /></a></div><h3>{project.title}</h3><p>{project.description}</p><div className="chip-list compact">{project.technologies.map(technology => <span key={technology}>{technology}</span>)}</div><ul className="evidence-list">{project.evidence.map(item => <li key={item}><Check size={15} />{item}</li>)}</ul><div className="project-actions"><a className="text-link" href={project.github} target="_blank" rel="noreferrer">View on GitHub <ExternalLink size={15} /></a><button className="text-link screenshot-link" onClick={() => onImage(project.images)} aria-label={`Open ${project.title} screenshots`} title="Open screenshots"><Images size={15} /></button></div></div></article>; }

function Projects() { const [lightbox, setLightbox] = useState(null); const openImages = images => setLightbox({ images, index: 0 }); return <section id="projects" className="section-shell section-block"><SectionHeading eyebrow="04 / Selected work" title="Proof over promises." copy="A focused selection of automation work, with the testing surface brought to the front." /><div className="projects-grid">{portfolio.projects.map(project => <ProjectCard key={project.title} project={project} onImage={openImages} />)}</div>{lightbox && <Lightbox images={lightbox.images} index={lightbox.index} onChange={index => setLightbox(current => ({ ...current, index }))} onClose={() => setLightbox(null)} />}</section>; }

function Certifications() { return <section id="certifications" className="section-shell section-block"><SectionHeading eyebrow="05 / Certifications" title="Always learning the craft." /><div className="cert-grid">{portfolio.certifications.map((certificate, index) => <article className="cert-card" key={certificate.title}><div className="cert-icon"><Award size={20} /></div><span className="cert-index">0{index + 1}</span><p>{certificate.issuer}</p><h3>{certificate.title}</h3>{certificate.detail && <small>{certificate.detail}</small>}<a className="text-link" href={certificate.url} target="_blank" rel="noreferrer">{certificate.label} <ExternalLink size={15} /></a></article>)}</div></section>; }

function Education() { return <section id="education" className="section-shell section-block"><SectionHeading eyebrow="06 / Education" title="The foundation." /><div className="education-card"><div className="education-icon"><GraduationCap size={28} /></div><div><span className="date-tag">2023 - 2027 · Expected</span><h3>{portfolio.education.degree}</h3><p>{portfolio.education.institution}</p><span>{portfolio.education.affiliation}</span></div></div></section>; }

function Gallery() { return <section id="gallery" className="section-shell section-block"><SectionHeading eyebrow="07 / Gallery" title="The gallery is ready." copy="A quiet place for future moments, milestones, and behind-the-scenes glimpses." />{portfolio.gallery.length ? <div className="gallery-grid">{portfolio.gallery.map(item => <figure key={item.image}><img src={item.image} alt={item.caption || 'Gallery moment'} loading="lazy" /><figcaption>{item.caption}</figcaption></figure>)}</div> : <div className="gallery-empty"><div><Images size={30} /><h3>Gallery coming soon</h3></div></div>}</section>; }

function Contact() { return <section id="contact" className="contact-band"><div className="section-shell contact-inner"><div><p className="eyebrow">08 / Contact</p><h2>Let's make quality<br /><span className="gradient-text">a habit.</span></h2><p>Open to conversations around QA automation, software testing, and building better release confidence.</p></div><div className="contact-links"><a href={`mailto:${portfolio.person.email}`}><Mail size={18} />{portfolio.person.email}<ArrowUpRight size={15} /></a><a href={`tel:${portfolio.person.phone.replaceAll('-', '')}`}><MessageCircle size={18} />{portfolio.person.phone}<ArrowUpRight size={15} /></a><a href={portfolio.person.linkedin} target="_blank" rel="noreferrer"><BriefcaseBusiness size={18} />LinkedIn<ArrowUpRight size={15} /></a><a href={portfolio.person.github} target="_blank" rel="noreferrer"><Code2 size={18} />GitHub<ArrowUpRight size={15} /></a><a href={portfolio.person.instagram} target="_blank" rel="noreferrer"><FaInstagram size={18} />Instagram<ArrowUpRight size={15} /></a></div></div></section>; }

function App() { return <><Navbar /><main><Hero /><About /><Experience /><Metrics /><Skills /><Projects /><Certifications /><Education /><Gallery /><Contact /></main><footer className="footer section-shell"><a className="brand" href="#home"><span className="brand-mark">JB</span><span>Jayant<span className="brand-dot">.</span></span></a><p>© 2026 Jayant Bansal · Automation Test Engineer</p><div className="footer-links"><a href={portfolio.person.linkedin} target="_blank" rel="noreferrer" aria-label="Open LinkedIn"><BriefcaseBusiness size={16} /></a><a href={portfolio.person.github} target="_blank" rel="noreferrer" aria-label="Open GitHub"><Code2 size={16} /></a><a href={portfolio.person.instagram} target="_blank" rel="noreferrer" aria-label="Open Instagram"><FaInstagram size={16} /></a></div></footer></>; }

export default App;
